### PR TITLE
Document how to update the Nix flake derivation

### PR DESCRIPTION
**Pull request by jdbaldry**
Signed-off-by: Jack Baldry <jack.baldry@grafana.com>

### CODE REVIEW

**Comment by julienduchesne** [comment]
Is this something we could automate in the release workflow? https://github.com/grafana/jsonnet-language-server/blob/main/.github/workflows/release.yml

**Comment by jdbaldry** [comment]
Yeah I imagine we could write some glue for this. If time permits, I'll look at that today.

**Comment by jdbaldry** [comment]
So as I sat down to do this, I realized that we would really want the file to be updated and committed before the tag push that triggers the workflow. I've codified the steps for updating the Nix derivation but it still requires the nix command line tool to run.

**Review by julienduchesne — APPROVED** [review]
> So as I sat down to do this, I realized that we would really want the file to be updated and committed before the tag push that triggers the workflow. I've codified the steps for updating the Nix derivation but it still requires the nix command line tool to run.

That's fine. As long as it's documented 🙂. We can merge I'd like to try it out on a release tomorrow, if that's OK (I have 0.18 and some other fixes pending release already)

**Comment by jdbaldry** [comment]
Coolio! I realize that without prior use of Nix, this is a little awkward. Ping me if you have any difficulties.

**Pull request merged**
