### PR TITLE
feat: support for std.extVar variables

### PR DESCRIPTION
**Pull request by entombedvirus**
This PR uses the LSP dynamic configuration loading to support user-specified extVars.

### CODE REVIEW

**Comment by entombedvirus** [comment]
hey @julienduchesne, please let me know if you're interested in merging this PR. I didn't realize the CLA requirement until recently, which I have signed. 

I've been using my fork in my daily workflow w/o issues for the past few months.

I have another branch in which I added support for[ allowing users to change the jsonnet formatting options](https://github.com/grafana/jsonnet-language-server/blob/main/pkg/server/formatting.go#L20), but that builds on top of the `DidChangeConfigurationParams` support that this PR added. If you're interested, I can post a separate PR for that as well after this has been merged.

**Comment by julienduchesne** [comment]
Oops. Fell through my radar. I’ll review this this week

**Comment by julienduchesne** [comment]
👋 Perhaps you can help me. I've been checking this out and I can't make `DidChangeConfiguration` notifications reach the server using a vscode client. What client are you using?

**Comment by julienduchesne** [comment]
Works great! Thanks! I'll be able to leverage the configuration feature to get rid of the language server restart I'm using when changing settings in the vscode extension: https://github.com/grafana/vscode-jsonnet/blob/main/src/extension.ts#L150-L154

**Pull request merged**
